### ISSUE TITLE
Colors scroll into nothingness

### ISSUE THREAD

**Issue by majjejjam** [FineFindus/eyedropper#69] opened 2023-06-14 09:33 UTC
**The bug**
When you have selected enough colors for the list to the right to be scrollable, and you scroll down, the color previews disappear into nothingness.

**To Reproduce**
1. Pick many colors, or hold down Ctrl+R
2. Scroll down the color preview list
3. See error

**Expected behavior**
There should be a separator like when you scroll down in the About page.

**Screenshots**
![Skärmbild från 2023-06-14 11-32-44](https://github.com/FineFindus/eyedropper/assets/58899295/665925bc-854b-483c-a1c5-24d5fc15e318)
![Skärmbild från 2023-06-14 11-32-52](https://github.com/FineFindus/eyedropper/assets/58899295/64c22bdb-e9b8-40c3-a295-018a0b110da4)

**Comment by FineFindus** [comment] 2023-06-14 16:28
I'm not quite sure what you mean, as far as I can see the list works as intended. Do you mean that the headerbar does not show a shadow when scrolling up the list?

**Comment by FineFindus** [comment] 2023-06-17 15:28
Should be fixed in 7bf2820ee49efc1c170a31aa7e428920472f7366 (notice the undershoot/shadow on the scrolling list).

![History list with undershoot](https://github.com/FineFindus/eyedropper/assets/63370021/bb8cf5a5-550a-42ef-b845-dd123b843119)

**Closed by FineFindus** 2023-06-17 15:28 UTC
Labels: bug
