### ISSUE TITLE
ERROR eyedropper::window > Portal request didn't succeed: Other

### ISSUE THREAD

**Issue by afk-mario** [FineFindus/eyedropper#28] opened 2022-11-30 17:38 UTC
**Describe the bug**
Failed to pick the color under Sway

**To Reproduce**
Try to pick any color under sway

**Expected behavior**
To get the color info

**Information**

OS: Arch Linux x86_64 
Kernel: 5.15.80-1-lts 
WM: sway 
version: 0.4.0

<details>
  <summary>Debugging Information</summary>

```
Eyedropper: 0.4.0
Profile: 
Backend: Wayland
Sandboxed: true

OS:
 - Name: "GNOME"
 - Version: "43 (Flatpak runtime)"
 - GTK_THEME: "Unset"
 - Theme: "Default"
 - IconTheme: "Adwaita"

Flatpak:
 - Name: com.github.finefindus.eyedropper
 - Runtime: runtime/org.gnome.Platform/x86_64/43
 - Runtime commit: 750f3ba756dae491001b55fb71617759b2e5de65de45a39c10532407faac0a11
 - Arch: x86_64
 - Flatpak Version: 1.15.1

Libraries:
 - GTK: 4.8.2
 - Libadwaita: 1.2.0


```

</details>

**Comment by FineFindus** [comment] 2022-11-30 19:58
Thanks for the report, this is a known issue. The problem is that the [xdg-portal api](https://github.com/emersion/xdg-desktop-portal-wlr) used by wlroots, does not correctly implement the portal for picking colors. This is also an issue with other color pickers, such as [gcolor3](https://gitlab.gnome.org/World/gcolor3).
While this is not intended behavior when using Eyedropper, I think this issue belongs to the portal repo, please open it there. I'm closing this for now, if you disagree with my decision, feel free to reopen it.

**Closed by FineFindus** 2022-11-30 19:58 UTC
