### ISSUE TITLE
Color in eyedropper cycles rapidly as cursor moves

### ISSUE THREAD

**Issue by Vectornaut** [FineFindus/eyedropper#131] opened 2024-03-08 01:57 UTC
**Describe the bug**
Color in eyedropper cycles rapidly as cursor moves, and doesn't match color of pixel under cursor.

**To Reproduce**

1. Open the terminal to make an area of solid color on the screen.
2. Open Eyedropper and start color selection.
3. Move cursor slowly across terminal background.

**Expected behavior**
Color in eyedropper is constant, and matches terminal background color of terminal.

**Actual behavior**
Color in eyedroper cycles rapidly through apparently random colors. Clicking selects color shown in eyedropper, even if it has nothing to do with the color on the screen.

**Information**

OS: Ubuntu 22.04.4
Desktop: Gnome 42.9
Window manager: Wayland

Scale: 125%
Fractional scaling: on
Night light: on

**Comment by FineFindus** [comment] 2024-03-08 21:05
I'm not quite sure if I'm correctly understanding the issue, would it be possible for you to record a video of it?

**Comment by Vectornaut** [comment] 2024-03-08 23:27
Sure. I'm seeing the same issue in Gcolor3 and the terminal palette color picker. This screencast uses the latter, since I've removed both Flatpak and Eyedropper by now.

[eyedropper-color-flicker.webm](https://github.com/FineFindus/eyedropper/assets/12519587/5efac791-84e2-4893-8c7a-f561389e74b9)

**Comment by FineFindus** [comment] 2024-03-09 21:59
Thanks. Both due to the fact that this component is not directly controlled by Eyedropper, but by the desktop itself, and the fact that the problem occurs in multiple applications, I'm pretty sure it's not caused by Eyedropper. I think it would be best to report this to your distribution instead. I will close this for now, if it turns out that it is indeed caused by Eyedropper, feel free to reopen it.

**Closed by FineFindus** 2024-03-09 21:59 UTC
Labels: bug
