### ISSUE TITLE
Open the Color Picker Directly

### ISSUE THREAD

**Issue by rodrigoGA** [FineFindus/eyedropper#144] opened 2024-06-06 00:15 UTC
I would like to have the possibility to open the application directly in the color picker screen.  I think it would be very useful for those of us who use the application. 
Perhaps it could be done from the command line, allowing it to be integrated with a launcher like Ulauncher, which would be very helpful whenever we want to use it.

**Comment by FineFindus** [comment] 2024-06-06 05:35
Duplicate of #140.

**Closed by FineFindus** 2024-06-06 05:35 UTC
Labels: enhancement
