### ISSUE TITLE
Does not launch on Ubuntu 23.04 (Lunar Lobster)

### ISSUE THREAD

**Issue by Drostina** [FineFindus/eyedropper#73] opened 2023-07-03 09:18 UTC
**Describe the bug**

I understand there is a similar PopOS issue open here, but mine seems different has only just recently started and used to work perfectly. 

**To Reproduce**

Installed using flatpak, flatpak run gives the following:

```
flatpak run com.github.finefindus.eyedropper

(eyedropper:2): Gdk-WARNING **: 10:07:13.385: The program 'eyedropper' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 475 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Tried to run with: GDK_SYNCHRONIZE=1 like suggested, but doesn't give any more information

**Expected behavior**

Program starts up

**Information**

- OS: Ubuntu Lunar Lobster
- Desktop Environment: Gnome 44
- GTK-Theme/Adwaita-Style: Yaru
- Version: Latest Flatpak

Please do let me know if there is anything else I can provide

Many thanks

**Comment by FineFindus** [comment] 2023-07-03 13:15
As you noticed, this is a duplicate of https://github.com/FineFindus/eyedropper/issues/65. Please follow the steps there (run `flatpak run --env=RUST_LOG=trace --env=G_MESSAGES_DEBUG=all --share=ipc com.github.finefindus.eyedropper`). If the problem persists, please include debug information by following the steps at https://github.com/FineFindus/eyedropper/issues/65#issuecomment-1537171930 and re-open this one.

**Closed by FineFindus** 2023-07-03 13:15 UTC
Labels: bug, duplicate
