### ISSUE TITLE
Eyedropper Version 2.0.1 Flatpak - Color Picker Not Working on Pop!_OS 22.04 LTS (COSMIC/Wayland)

### ISSUE THREAD

**Issue by BiteClassroom** [FineFindus/eyedropper#163] opened 2024-09-26 00:35 UTC
**Describe the bug**
In Eyedropper Version 2.0.1 installed as a flatpak on Pop!_OS 22.04 LTS (COSMIC desktop environment running on Wayland), the application opens and allows me to switch between previously selected colors, but it does not allow me to pick a color from the desktop. The color picker functionality is non-functional in the COSMIC desktop on Wayland.

**To Reproduce**

1. Install Eyedropper Version 2.0.1 as a flatpak.
2. Open the application on Pop!_OS 22.04 LTS using the COSMIC desktop environment (Wayland).
3. Attempt to pick a color from the desktop.
4. Notice that while the application allows color switching, the color picker does not function.

**Expected behavior**
I expect the application to allow me to pick colors from the desktop, as intended by the color picker functionality, regardless of the desktop environment. It should work seamlessly with COSMIC and Wayland in Pop!_OS 22.04 LTS.

**Environment:**

    OS: Pop!_OS 22.04 LTS x86_64
    Desktop Environment: COSMIC
    Host: VivoBook_ASUSLaptop X513IA_M513IA 1.0
    Wayland: Running on Wayland
    Application Version: Eyedropper Version 2.0.1 (installed as flatpak)

**Comment by FineFindus** [comment] 2024-09-26 19:02
Duplicate of https://github.com/FineFindus/eyedropper/issues/154. 
Though it should have shown a warning page if color picking isn't supported, I wonder why it didn't. Could you please run `dbus-send --session --type=method_call --print-reply --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.DBus.Introspectable.Introspect`?

**Closed by FineFindus** 2024-09-26 19:02 UTC
Labels: bug
