### ISSUE TITLE
Misrendered SVG icon in KDE plasma

### ISSUE THREAD

**Issue by IkelAtomig** [FineFindus/eyedropper#178] opened 2024-11-21 05:52 UTC
In KDE Plasma, the Icon of the app is misrendered due to unsupported SVG elements in KDE.

![image](https://github.com/user-attachments/assets/93ce2e05-4a6f-44f4-bafe-b07a1c666bee)

It would be aesthetically fixed if icon file is either a png or jpeg than svg. 

More details here : https://discuss.kde.org/t/can-you-fix-gnome-icons-black-frames/1854

**Comment by FineFindus** [comment] 2024-11-21 07:01
Thanks for the report, but as detailed in the forum post, this is caused by a KDE bug, it would be better to be fixed by them, as it affects all icons.

**Closed by FineFindus** 2024-11-21 07:01 UTC
Labels: bug
